[package]
name = "crabbletalk-afpd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
pnet = "0.29.0"
winreg = "0.10.1"

[dependencies.tokio] 
version = "1"
features = ["full"] 
